### ISSUE TITLE
How to cite Java-parser in article/paper

### ISSUE THREAD

**Issue by omkarendra** [javaparser/javaparser-maven-sample#1]
Hi,
I am not able to find a reference for Java parser, so that I can cite it. As I have used it in my work.
Please, provide me any pointer or information that I can use to cite it in a research article.

Thank you.

**Comment by SmiddyPence** [comment]
The main website is: https://javaparser.org/

The main code repository is: https://github.com/javaparser/javaparser

The main documentation and book is: https://leanpub.com/javaparservisited

**Comment by matozoid** [comment]
Also here: https://github.com/javaparser/javaparser/issues/2148
