### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/javaparser/ast/visitor/GenericVisitor

### ISSUE THREAD

**Issue by spilehchiha** [javaparser/javaparser-maven-sample#2]
Hello there,
I am trying to run the maven_sample project, namely, the LogicPositivizer.java file, but the error that I receive is as follows:

```
Error: Unable to initialize main class App
Caused by: java.lang.NoClassDefFoundError: com/github/javaparser/ast/visitor/GenericVisitor
```
The commands I run are:

`mvn clean install
java -cp target/<name-of-jar-file> com.yourorganization.maven_sample.LogicPositivizer`

Does anybody know here this issue might use from? It happens both while using Intellij IDEA and in terminal.

**Comment by matozoid** [comment]
Ah, I'm only running this by running the class directly from Intellij. Needs more instructions, I guess.

**Comment by matozoid** [comment]
Okay, I've changed the pom to create an executable jar, and added some instructions. Can you try again?

I don't know why it doesn't work in Intellij, since "it works for me" - and it should work for you. Try opening the Maven tab and checking that all dependencies are there without errors.

**Comment by spilehchiha** [comment]
It works now.
What I'm really trying to do is that I have lots of Java snippets and I need to generate ASTs for each of them with javaparser, Is there any other concrete example like this one to show how it's done?

Thanks a lot, again. You've been really quick and helpful!

**Comment by matozoid** [comment]
Is there anything consistent about those snippets? There are methods for parsing statements, expressions, etc. If there is no consistency you might want to try parsing it with each of these methods until one of them works :-) (Like "is it a class? No. Is it an expression? No. Is it a statement? Yes."

**Comment by spilehchiha** [comment]
Well, I guess I stated my purpose not in the clearest fashion possible.
By snippets I meant files. :-)

**Comment by matozoid** [comment]
Okay, then I think the answer is `SourceRoot`. It's "how do I parse a bunch of Java files in a directory", right?

**Comment by spilehchiha** [comment]
I didn't know about `SourceRoot`.
Yes. The question was exactly in regard to the problem of parsing multiple files in one directory.
I sincerely thank you for that.You are immensely helpful. I'll take a shot at that today!

**Comment by matozoid** [comment]
Good luck! Open a new issue or come to Gitter if you need more information.
