### ISSUE TITLE
request javaparser gradle sample

### ISSUE THREAD

**Issue by dkkacceler** [javaparser/javaparser-maven-sample#3]
SourceRoot can not use in gradle

**Comment by matozoid** [comment]
Hi! If you would like a sample project setup like this Maven setup, but for Gradle, that would be a nice project for someone who is good with Gradle.

You say that you can not use SourceRoot in Gradle. What is the error?

**Comment by dkkacceler** [comment]
Exception in thread "main" java.lang.IllegalArgumentException: Only directories are allowed as root path: /Users/xxxxxxxxx/javascan/scan-easy/build/classes/src/main/resources
	at com.github.javaparser.utils.SourceRoot.<init>(SourceRoot.java:71)
	at com.pinduoduo.scaneasy.LogicPositivizer.main(LogicPositivizer.java:23)

**Comment by dkkacceler** [comment]
When using gradle, the resource path should be Resources. I don't know how to create SourceRoot using Resources.

**Comment by matozoid** [comment]
Alright, I don't really know what's going on here. I thought Gradle used the same directory structure as Maven.

**Comment by MysterAitch** [comment]
> 
> 
> When using gradle, the resource path should be Resources. I don't know how to create SourceRoot using Resources.

Just to clarify: Is this attempting to use javaparser to parse a gradle project? or using gradle to build javaparser? or something else?

**Comment by MysterAitch** [comment]
A working gradle sample project has been create now :) 

It is essentially identical to the maven sample, though there is a small tweak to the logic (and it'll be removed once it has been added into the main repo).

https://github.com/javaparser/javaparser-gradle-sample

@dkkacceler and others -- if you have any gradle problems, please create an issue over there :)

**Comment by MysterAitch** [comment]
Sidenote: Turns out that this was a bug / issue.


```
Exception in thread "main" java.lang.IllegalArgumentException: Only directories are allowed as root path: /Users/xxxxxxxxx/javascan/scan-easy/build/classes/src/main/resources
at com.github.javaparser.utils.SourceRoot.(SourceRoot.java:71)
at com.pinduoduo.scaneasy.LogicPositivizer.main(LogicPositivizer.java:23)
```


The reason for this exception being thrown is because gradle uses a different directory structure to maven, meaning that a different number of parent directories needs to traversed (it is a bit of an odd/cryptic error message though). 

A workaround is implemented here: 

https://github.com/javaparser/javaparser-gradle-sample/commit/ec06c83b196d01d18fd10090e85b31455e5ce96c

**Comment by matozoid** [comment]
I think @jlerbsc can be involved here.

**Comment by jlerbsc** [comment]
It seems to me that the modification is integrated into the javaparser gradle sample project, which illustrates how to use the Util.gradleModuleRoot method. This is a development example that you should integrate into your own project. This type of method is not intended to be integrated into the javaparser project and the existing mavenModuleRoot method is not intended to be used by users either. This method is only used to facilitate unit testing.

**Comment by Sylordis** [comment]
Alright, this is good to know because seeing the `mavenModuleRoot` was a bit confusing and looking for the exception on the web only brings here. It shall be integrated into the project then! Thanks.
