### ISSUE TITLE
identation and comments are not preserved

### ISSUE THREAD

**Issue by gantsevdenis** [javaparser/javaparser-maven-sample#4]
When saving the modified source, Javaparser also adds newlines, and moves comments from end of line to above the line.
This is harmless, but when ran agains a large code base it would produces a gigantic commit change, while only a small fraction of it is useful.

**Comment by matozoid** [comment]
Hi! That's what the LexicalPreservingPrinter is for, but since this sample is only here to show the project setup, it uses the pretty printer. It's easier to run.
